# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS

  pod 'Alamofire'  
  pod 'SwiftyJSON'

  pod 'NMapsMap'
  pod 'SwiftSoup'

  pod 'Kingfisher', '~> 5.0'
  pod 'Kingfisher/SwiftUI'

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  pod 'GoogleAPIClient/Gmail'

end
